# Generated by Django 3.1.1 on 2020-11-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeLine',
            new_name='Milestone',
        ),
        migrations.RenameModel(
            old_name='SubWorkPackages',
            new_name='SubWorkPackage',
        ),
        migrations.RenameModel(
            old_name='WorkPackages',
            new_name='WorkPackage',
        ),
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
