# Generated by Django 3.1.1 on 2020-11-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201116_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subworkpackage',
            old_name='time_line',
            new_name='milestone_Id',
        ),
        migrations.RenameField(
            model_name='workpackage',
            old_name='time_line',
            new_name='milestone_Id',
        ),
    ]
