# Generated by Django 3.1.1 on 2020-11-18 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201118_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkpackage',
            name='phase_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.phase'),
        ),
        migrations.AddField(
            model_name='workpackage',
            name='phase_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.phase'),
        ),
    ]
