# Generated by Django 3.1.1 on 2020-11-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201120_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledetail',
            name='role',
            field=models.CharField(choices=[('Product Management', 'Product Management'), ('Sales', 'Sales'), ('Engineer', 'Engineer'), ('General', 'General'), ('Production', 'Production'), ('Purchase', 'Purchase'), ('Testing', 'Testing'), ('PrototypeShop', 'PrototypeShop'), ('Logistic', 'Logistic')], max_length=200, null=True),
        ),
    ]
