# Generated by Django 3.1.1 on 2021-03-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210208_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='phase_Id',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='project_Id',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='project_Id',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='project_Id',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subworkpackage',
            name='milestone_Id',
        ),
        migrations.RemoveField(
            model_name='subworkpackage',
            name='phase_Id',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='milestone_Id',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='phase_Id',
        ),
        migrations.DeleteModel(
            name='ManagerGroup',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
