# Generated by Django 3.1.1 on 2021-03-25 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_auto_20210323_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPackage0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('date_of_state1', models.DateField(auto_now_add=True, null=True)),
                ('date_of_state2', models.DateField(blank=True, null=True)),
                ('date_of_state3', models.DateField(blank=True, null=True)),
                ('date_of_state4', models.DateField(blank=True, null=True)),
                ('date_of_start', models.DateField(blank=True, null=True)),
                ('date_of_end', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('actual_date_of_start', models.DateField(blank=True, null=True)),
                ('actual_date_of_end', models.DateField(blank=True, null=True)),
                ('efforts_actual', models.IntegerField(null=True)),
                ('efforts_planned', models.IntegerField(null=True)),
                ('border_color', models.CharField(default='#ffffff', max_length=8)),
                ('project_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.state')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPackage1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('date_of_state1', models.DateField(auto_now_add=True, null=True)),
                ('date_of_state2', models.DateField(blank=True, null=True)),
                ('date_of_state3', models.DateField(blank=True, null=True)),
                ('date_of_state4', models.DateField(blank=True, null=True)),
                ('date_of_start', models.DateField(blank=True, null=True)),
                ('date_of_end', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('actual_date_of_start', models.DateField(blank=True, null=True)),
                ('actual_date_of_end', models.DateField(blank=True, null=True)),
                ('efforts_actual', models.IntegerField(null=True)),
                ('efforts_planned', models.IntegerField(null=True)),
                ('border_color', models.CharField(default='#ffffff', max_length=8)),
                ('project_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.state')),
                ('workPackage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.workpackage0')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPackage2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('date_of_state1', models.DateField(auto_now_add=True, null=True)),
                ('date_of_state2', models.DateField(blank=True, null=True)),
                ('date_of_state3', models.DateField(blank=True, null=True)),
                ('date_of_state4', models.DateField(blank=True, null=True)),
                ('date_of_start', models.DateField(blank=True, null=True)),
                ('date_of_end', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('actual_date_of_start', models.DateField(blank=True, null=True)),
                ('actual_date_of_end', models.DateField(blank=True, null=True)),
                ('efforts_actual', models.IntegerField(null=True)),
                ('efforts_planned', models.IntegerField(null=True)),
                ('border_color', models.CharField(default='#ffffff', max_length=8)),
                ('project_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.state')),
                ('workPackage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.workpackage1')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPackage3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('date_of_state1', models.DateField(auto_now_add=True, null=True)),
                ('date_of_state2', models.DateField(blank=True, null=True)),
                ('date_of_state3', models.DateField(blank=True, null=True)),
                ('date_of_state4', models.DateField(blank=True, null=True)),
                ('date_of_start', models.DateField(blank=True, null=True)),
                ('date_of_end', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('actual_date_of_start', models.DateField(blank=True, null=True)),
                ('actual_date_of_end', models.DateField(blank=True, null=True)),
                ('efforts_actual', models.IntegerField(null=True)),
                ('efforts_planned', models.IntegerField(null=True)),
                ('border_color', models.CharField(default='#ffffff', max_length=8)),
                ('project_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.state')),
                ('workPackage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.workpackage2')),
            ],
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='department',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='project_Id',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='responsible',
        ),
        migrations.DeleteModel(
            name='SubWorkPackage',
        ),
        migrations.DeleteModel(
            name='WorkPackage',
        ),
    ]
