# Generated by Django 3.1.1 on 2021-03-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210325_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='backward_movement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='state',
            name='forward_movement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='state',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.usertype'),
        ),
        migrations.AddField(
            model_name='userprofiledetail',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.usertype'),
        ),
    ]
