# Generated by Django 2.0.2 on 2020-11-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201123_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiledetail',
            name='department',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
