# Generated by Django 3.1.1 on 2021-03-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210327_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
