# Generated by Django 3.1.1 on 2021-03-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_state_order'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='workpackage3',
            order_with_respect_to='responsible',
        ),
    ]
