# Generated by Django 3.1.1 on 2020-11-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201123_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiledetail',
            name='role',
        ),
    ]
