# Generated by Django 3.1.1 on 2020-12-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_userprofiledetail_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='project_Id',
        ),
        migrations.AddField(
            model_name='subworkpackage',
            name='priority',
            field=models.IntegerField(choices=[('LOW', 1), ('MEDIUM', 2), ('HIGH', 3)], default=1),
        ),
    ]
