# Generated by Django 3.1.1 on 2020-12-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201210_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkpackage',
            name='actual_date_of_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subworkpackage',
            name='actual_date_of_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subworkpackage',
            name='efforts_actual',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subworkpackage',
            name='efforts_planned',
            field=models.IntegerField(null=True),
        ),
    ]
