# Generated by Django 3.1.1 on 2021-03-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_workpackage3_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workpackage0',
            old_name='project_Id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='workpackage1',
            old_name='project_Id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='workpackage2',
            old_name='project_Id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='workpackage3',
            old_name='project_Id',
            new_name='project',
        ),
    ]
