# Generated by Django 3.1.1 on 2020-12-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201213_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkpackage',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
