# Generated by Django 3.1.1 on 2021-04-03 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_auto_20210329_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workpackage0',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workpackage1',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workpackage2',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workpackage3',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignee1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workpackage0',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignee2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workpackage1',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignee3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workpackage2',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignee4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workpackage3',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignee5', to=settings.AUTH_USER_MODEL),
        ),
    ]
