# Generated by Django 3.1.1 on 2020-12-29 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_subworkpackage_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subworkpackage',
            name='state',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.state'),
        ),
    ]
