# Generated by Django 3.1.1 on 2021-01-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20201229_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkpackage',
            name='date_of_end_year_week',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subworkpackage',
            name='date_of_start_year_week',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
