# Generated by Django 3.1.1 on 2021-04-04 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210403_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpackage3',
            name='status',
        ),
        migrations.AddField(
            model_name='workpackage3',
            name='emp_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_status', to='api.status'),
        ),
        migrations.AddField(
            model_name='workpackage3',
            name='manager_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_status', to='api.status'),
        ),
    ]
