# Generated by Django 3.1.1 on 2021-01-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210101_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkpackage',
            name='date_of_state1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subworkpackage',
            name='date_of_state2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subworkpackage',
            name='date_of_state3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subworkpackage',
            name='date_of_state4',
            field=models.DateField(blank=True, null=True),
        ),
    ]
