# Generated by Django 3.1.1 on 2021-04-16 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210416_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpackage3',
            name='manager_status',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_status', to='api.status'),
        ),
    ]
