# Generated by Django 3.1.1 on 2021-01-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210123_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subworkpackage',
            name='date_of_state1',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
