# Generated by Django 3.1.1 on 2021-04-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210416_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='backward_movement',
            new_name='backward_movement_emp',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='forward_movement',
            new_name='backward_movement_manager',
        ),
        migrations.AddField(
            model_name='state',
            name='forward_movement_emp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='state',
            name='forward_movement_manager',
            field=models.BooleanField(default=True),
        ),
    ]
