# Generated by Django 3.1.1 on 2021-01-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210123_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subworkpackage',
            name='date_of_end_year_week',
        ),
        migrations.RemoveField(
            model_name='subworkpackage',
            name='date_of_start_year_week',
        ),
    ]
