# Generated by Django 3.1.1 on 2021-04-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210416_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpackage3',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
