# Generated by Django 3.1.1 on 2021-04-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210416_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workpackage3',
            old_name='date_of_end',
            new_name='planned_date_of_end',
        ),
        migrations.RenameField(
            model_name='workpackage3',
            old_name='date_of_start',
            new_name='planned_date_of_start',
        ),
    ]
