# Generated by Django 3.1.1 on 2021-04-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210417_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledetail',
            name='user_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.usertype'),
        ),
    ]
