# Generated by Django 3.1.1 on 2021-05-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210505_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage3',
            name='inputFrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='input_from', to='api.workpackage3'),
        ),
    ]
