# Generated by Django 3.1.1 on 2021-05-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_workpackage3_inputfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage3',
            name='inputFile',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
