# Generated by Django 3.1.1 on 2021-05-06 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0034_auto_20210506_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPackage2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('planned_date_of_start', models.DateField(blank=True, null=True)),
                ('planned_date_of_end', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('actual_date_of_start', models.DateField(blank=True, null=True)),
                ('actual_date_of_end', models.DateField(blank=True, null=True)),
                ('efforts_actual', models.IntegerField(null=True)),
                ('efforts_planned', models.IntegerField(null=True)),
                ('inputFile', models.FileField(blank=True, upload_to='documents/')),
                ('border_color', models.CharField(default='#f5f5f5', max_length=8)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator4', to=settings.AUTH_USER_MODEL)),
                ('inputFrom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='input_from', to='api.workpackage2')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignee4', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.state')),
            ],
            options={
                'order_with_respect_to': 'responsible',
            },
        ),
        migrations.AddField(
            model_name='workpackage3',
            name='parentPackage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.workpackage2'),
        ),
    ]
